name: Deploy our Eshop to EC2 via Ansible

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  #Deploy our Eshop to new AWS EC2 instance
  DeployToEC2:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Instal Ansible
        run: |
          pip3 install boto boto3 ansible

      - name: Prepare Ansible Group Vars and SSH Private key
        run: |
          printf 'aws_access_key: ${{ secrets.ACCESS_KEY }}\n' >> ./ansible/group_vars/all/aws.yml
          printf 'aws_secret_key: ${{ secrets.SECRET_KEY }}\n' >> ./ansible/group_vars/all/aws.yml
          printf 'security_token: ${{ secrets.SESSION_KEY }}\n' >> ./ansible/group_vars/all/aws.yml
          touch ./ansible/devops.pem
          chmod 400 ./ansible/devops.pem
          printf '${{ secrets.SSH_PRIVATE_KEY }}' >> ./ansible/devops.pem

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook ./ansible/ec2_deploy.yml --user ec2-user --key-file ./ansible/devops.pem
