name: Deploy our Eshop to EC2 via Ansible

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  #Deploy our Eshop to new AWS EC2 instance
  DeployToEC2:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Instal Ansible
        run: pip3 install boto boto3 ansible

      - name: Prepare private key
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} > ./ansible/devops.pem
          chmod 400 ./ansible/devops.pem

      - name: Create Ansible vars
        run: |
          echo 'aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}\n' >> ./ansible/group_vars/all/aws.yml
          echo 'aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}\n' >> ./ansible/group_vars/all/aws.yml
          echo 'security_token: ${{ secrets.SECURITY_KEY }}\n' >> ./ansible/group_vars/all/aws.yml


      - name: Run Ansible playbook
        run: |
          ansible-playbook ./ansible/ec2_deploy.yml --user ec2-user --key-file ./ansible/devops.pem
