name: Deploy our Eshop to EC2 via Ansible

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  #Deploy our Eshop to new AWS EC2 instance
  DeployToEC2:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Instal Ansible
        run: pip3 install boto boto3 ansible

      - name: ansible-playbook ec2_deploy.yml --user ec2-user --key-file ./devops.pem
